### ISSUE TITLE
Best compatibility option

### ISSUE THREAD

**Issue by kieron** [rhythmagency/rhythm.umbraco7.font-awesome-icon-picker#10]
Hi, does the plugin have anything in place for compatibility, sometimes Font Awesome requires a different precursor to the class, for example;

`<i class="far @CurrentPage.theIcon"></i>`

In the above, if i use a [_regular star_ ](https://fontawesome.com/icons/star?style=regular) it requires a '_far_' precursor, but if i pick fa-book, it won't render that using _'far'_ and I just get the ? icon, so my question, should i preface my insert with far, fas, fa etc?

Cheers

Edit;

Ive just noticed in the source on line 20, when you return the HTML, you **do** add 'fa' to the beginning of _value.text._

So should that line not add the fa precursor? which if you used in conjunction with a FA shim would work fine.

Edit; update 3, i realise now that the return on line 20 is for the umbraco picker, so i guess my initial question is answered by using a FA shim.

**Comment by Nicholas-Westby** [comment]
I usually just copy all the files for this to whatever project I'm working on, then modify it to suit my needs for whatever icon font(s) I happen to be using (e.g., font awesome, icomoon).
